logging:
  file: ./logFile.log

#  level:
#    root: debug
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_security?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&nullNamePatternMatchesAll=true&useSSL=true
    username: user
    password: 1234
#     driver-class-name: oracle.jdbc.OracleDriver
#     url: jdbc:oracle:thin:@192.168.8.136:1521:XE
#     username: QQQ
#     password: 7777
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update #生成实体类策略 #create-drop  #update
    show-sql: true #自动生成实体类
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.Oracle10gDialect
#    open-in-view: true
  devtools:
    restart:
      enabled: false  #热部署
      additional-paths: src/main/java #热部署-设置重启的目录
  session:
    store-type: REDIS
  redis:
    password: 1qazxsw2!
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#热部署-classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude=WEB-INF/**

#--------------JPA----------------
#无修改命名
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#遇到大写字母 加”_”的命名
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#自动生成实体类
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

custom-config:
  security:
    login-processing-url: /loginProcess
  log:
    mode: dev